version: "3"

services:
  container-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: juniorjohndoejd/mac-audiobot:0.0.23
    container_name: audiobot_api
    env_file: .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    # command: tail -f /dev/null