# Generated by Django 4.1 on 2024-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="thread_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
