# Generated by Django 4.1 on 2024-10-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_chatsession_thread_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
